### ISSUE TITLE
Make Landsat/S2 available on public RaPP

### ISSUE THREAD

**Issue by JohnLeys** [aus-groundcover/georapp-config#10]
Move the Landsat/S2 from Test to be available on public RaPP.

- [x] In catalogue, Vegetation cover -Landsat/Sentinel. Move the three seasonal JRSRP items to bottom of list
- [x] Connect the OWS Test1 item to replace the current CSIRO monthly Total Vegetation Cover 
- [x]  Connect the OWS Test1 item to replace the current CSIRO monthly Fractiona Cover

**Comment by mpaget** [comment]
Closed via #16 and EASI OWS update.
