### ISSUE TITLE
Process the archive for Landsat/S2 

### ISSUE THREAD

**Issue by JohnLeys** [aus-groundcover/georapp-config#11]
Based on testing using the 
- [https://cmi.ga.gov.au/data-products/dea/693/dea-waterbodies-landsat](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcmi.ga.gov.au%2Fdata-products%2Fdea%2F693%2Fdea-waterbodies-landsat&data=05%7C01%7C%7C095b7671ae084ed51e6008db3bb47e3a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638169418891455367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fxKJIj3GgFSYoSOThWDHa4dlohXMSR83fyZns%2BdiVYQ%3D&reserved=0)
-  new DEA Sentinel-2 ARD collection 3 product with the new Sentinel-2 cloud mask (s2cloudless) and without our additional brightness mask.

Process a visible RGB layer (the red, green and blue bands from the monthly LS/S-2 medoid) and the corresponding Total Cover and Fractional Cover RGB layers.

**Comment by mpaget** [comment]
Completed as OWS Test-1 product
