### ISSUE TITLE
Rainfall data update - URGENT

### ISSUE THREAD

**Issue by JohnLeys** [aus-groundcover/georapp-config#18]
When you do a drill on the cover for a time series, rainfall is also reported.

Rainfall data is only up to 21/4/22.  See https://map.geo-rapp.org/#share=s-bXzEFxxX1Qdi0Es90I9gILzxa8x

Can we get the updated data by Friday included, please

**Comment by mpaget** [comment]
Hi John, These rainfall data are from CHIRPS and are prepared on the NCI. Its a piece of code I've avoided updating as a lower priority versus the all the other upgrades we've done. I've looked at the code and its probably straight forward to update.
CHIRPS source: https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_dekad/netcdf/

**Comment by mpaget** [comment]
The CHIRPS data have been updated. It needs to be indexed by the GSKY service; I don't know how or the frequency of its updates. I'll check after the weekend and chase it up if need be.
